### ISSUE TITLE
Count of Animals

### ISSUE THREAD

**Issue by MitzyTorres** [tracefirst/usaha_committee#15]
There should be a property AnimalCount (integer > 0) on the Animal element. Some CVIs do not have animals enumerated per head - like swine or poultry, where the animals by "groups". Even Bovine CVIs are sometimes filled in on the CVIs as a group and not individually - right, wrong or indifferent. 

I have seen GVL animal entries for cattle where 
count = 486 
Animal ID =  32BBE5001 to 32BBE5486 (486 animals)

**Comment by mmcgrath** [comment]
This has been stagnant for a number of years and will be closed on 2 Sept unless objections are raised.
