### ISSUE TITLE
Capture Animal non-Accession/Test data like vaccination

### ISSUE THREAD

**Issue by MitzyTorres** [tracefirst/usaha_committee#29]
Some CVIs include vaccination information (Bruc, TB, Rabies- for small animals):
Type = ex: Brucellosis, TB, Rabies, etc
Date = date of vaccination; optional most probably, if vaccination date is unknown

**Comment by mmcgrath** [comment]
Phone call 8/17/16 - It was agreed that this isn't in scope for now. However, if there is a case where there is someone wants to send this data, we can reopen the issue.
