### ISSUE TITLE
Looking for guidance...premid for lab

### ISSUE THREAD

**Issue by nephiharvey** [tracefirst/usaha_committee#34]
In the code segment below:

 <xs:complexType name="AccessionType">
        xs:sequence
            <xs:element name="Laboratory" minOccurs="1" maxOccurs="1">
                xs:complexType
                    xs:sequence
                        <xs:element name="LabName" type="xs:string" minOccurs="0" maxOccurs="1"/>
                        <xs:element name="PremId" type="PremIdType" minOccurs="0" maxOccurs="1">
                            xs:annotation
                                xs:documentationThis is the Premises ID for the Laboratory. If it is an in-field test, then the premises ID of the farm on which the tests were performed should be used./xs:documentation
                            /xs:annotation
                        /xs:element

The implication that the PremID should be used for the lab id for in field tests.  Many (I dare say most) locations don't have a PremID.  If we box ourselves into this restriction, what about the exceptions.  We don't need to actually enter any value as minOccurs="0", but comments would be welcome.

**Comment by mmcgrath** [comment]
I think this was resolved - there is an InfieldTest boolean to explicitly indicate if the test was infield or not. And the PremID in the Laboratory is optional.
