### ISSUE TITLE
Additional Tags

### ISSUE THREAD

**Issue by nephiharvey** [tracefirst/usaha_committee#38]
Hello All:
  We have been working on a test XML creation from our software and have identified the following eCVI fields that we are collecting and printing on the eCVI that currently have no associated tags in the standard.  Comment is welcome.  Thanks,
Nephi

FIELDS THAT I CAN’T FIND IN THE XSD THAT WE HAVE IN THE MOBILE PROGRAM:
Tests And Results -> Vaccination
Tests And Results -> Treatment-Date, Product and Reason
Legible Copies (Area Tab)
Test Record Numbers (Area Tab)
Herd Flock # (Flock Tab)
Bruc Vac (Animal Tab)
Tube# (animal Tab)
 (All CARRIER INFORMATION AT ALL – CARRIER TAB)
Intra-Inter State travel CHB (Carrier)
Carrier Method AIR/RAIL/CAR/Other (Carrier)
Carrier Method Other (Carrier)
Vet Email (Preferences)
Vet Comments (Comments)

**Comment by mkm1879** [comment]
On the national traceability call just now the issue of Swine Premises ID tags came up again.  It was clarified that what must be recorded on a CVI for interstate movement is the Premises Tag Number (PIN) PLUS a unique management number.  So this would be an ID type something like "PIN + Mgt"  Yuck.  But that is the current rule.

**Comment by mmcgrath** [comment]
There has been no movement on this for some time. It was agreed on today's call to close it - if any of the original issues want to be reopened, please open a new issue.
